// playgrounds/vite-react/src/App.tsx
import { useCallback, useEffect, useMemo, useState } from "react";
import type { QueryClient } from "@tanstack/react-query";
import { createPublicClient, http } from "@ivem/core";
import {
  createConfig,
  iwallet,
  mainnet,
  IvemProvider,
  useAccount,
  useCallContract,
  useWriteContract,
  useChainId,
  useConnect,
  useDisconnect,
  useReconnect,
  useSendTransaction,
  useSignMessage,
  useWaitForTransactionReceipt,
} from "@ivem/kit-react";

const config = createConfig({
  chains: [mainnet],
  connector: iwallet(),
});

const publicClient = createPublicClient({
  chain: mainnet,
  transport: http(),
});

type AppProps = {
  queryClient?: QueryClient;
};

export default function App({ queryClient }: AppProps) {
  return (
    <IvemProvider config={config} reconnectOnMount queryClient={queryClient}>
      <DemoPage />
    </IvemProvider>
  );
}

function formatResult(value: unknown) {
  if (value == null) return "";
  if (typeof value === "string") return value;
  if (value instanceof Error) {
    const code =
      typeof (value as Error & { code?: unknown }).code === "number"
        ? (value as Error & { code: number }).code
        : undefined;
    const baseMessage = code != null ? `[${code}] ${value.message}` : value.message;
    return value.stack ? `${baseMessage}\n${value.stack}` : baseMessage;
  }
  try {
    return JSON.stringify(value, null, 2);
  } catch {
    return String(value);
  }
}

function DemoPage() {
  const account = useAccount();
  const chainId = useChainId();
  const connect = useConnect();
  const reconnect = useReconnect();
  const disconnect = useDisconnect();
  const signMessage = useSignMessage();
  const sendTransaction = useSendTransaction();
  const {
    data: txReceipt,
    isLoading: isWaitingReceipt,
    error: waitReceiptError,
  } = useWaitForTransactionReceipt({
    hash: sendTransaction.data?.hash ?? "",
    enabled: Boolean(sendTransaction.data?.hash),
  });
  const writeContract = useWriteContract();
  const callContract = useCallContract();

  const [walletInstalled, setWalletInstalled] = useState(false);
  const [lastError, setLastError] = useState<string>("");
  const [eventLogs, setEventLogs] = useState<
    Array<{ id: number; time: string; event: string; payload: string }>
  >([]);

  const [message, setMessage] = useState("Hello from Ivem Kit vite-react");
  const [to, setTo] = useState("");
  const [amount, setAmount] = useState("1");
  const [memo, setMemo] = useState("sent by Ivem Kit vite-react");
  const [contract, setContract] = useState("token.iost");
  const [action, setAction] = useState("transfer");
  const [argsText, setArgsText] = useState(
    '["iost", "", "", "1", "write demo"]'
  );

  const [nodeInfo, setNodeInfo] = useState<unknown>(null);
  const [isLoadingNodeInfo, setIsLoadingNodeInfo] = useState(false);

  const appendEventLog = useCallback((event: string, payload: unknown) => {
    let payloadText = "";
    if (typeof payload === "string") payloadText = payload;
    else {
      try {
        payloadText = JSON.stringify(payload);
      } catch {
        payloadText = String(payload);
      }
    }

    setEventLogs((prev) =>
      [
        {
          id: Date.now() + Math.floor(Math.random() * 10000),
          time: new Date().toLocaleTimeString(),
          event,
          payload: payloadText,
        },
        ...prev,
      ].slice(0, 80)
    );
  }, []);

  useEffect(() => {
    const checkWallet = () => {
      setWalletInstalled(Boolean(window.IWalletJS?.isIWalletJS));
    };

    checkWallet();
    window.addEventListener("focus", checkWallet);
    return () => window.removeEventListener("focus", checkWallet);
  }, []);

  useEffect(() => {
    const provider = window.IWalletJS;
    if (!walletInstalled || !provider?.isIWalletJS) return;

    const events = [
      "accountChanged",
      "accountsChanged",
      "networkChanged",
      "pending",
      "success",
      "failed",
    ] as const;

    const unbinds = events.map((event) => {
      const handler = (payload: unknown) => appendEventLog(event, payload);
      provider.on?.(event, handler);
      return () => {
        provider.off?.(event, handler);
        provider.removeListener?.(event, handler);
      };
    });

    return () => {
      for (const unbind of unbinds) unbind();
    };
  }, [appendEventLog, walletInstalled]);

  useEffect(() => {
    if (account.address) {
      setArgsText(
        JSON.stringify(["iost", account.address, "bob", "1", "write demo"])
      );
    }
  }, [account.address]);

  const requestErrors = useMemo(() => {
    return [
      connect.error,
      disconnect.error,
      signMessage.error,
      sendTransaction.error,
      waitReceiptError,
      writeContract.error,
      callContract.error,
    ]
      .filter(Boolean)
      .map((x) => formatResult(x));
  }, [
    callContract.error,
    connect.error,
    disconnect.error,
    sendTransaction.error,
    waitReceiptError,
    signMessage.error,
    writeContract.error,
  ]);

  async function handleConnect() {
    setLastError("");
    try {
      await connect.mutateAsync();
    } catch (error) {
      setLastError(formatResult(error));
    }
  }

  async function handleReconnect() {
    setLastError("");
    try {
      await reconnect.mutateAsync();
    } catch (error) {
      setLastError(formatResult(error));
    }
  }

  async function handleDisconnect() {
    setLastError("");
    try {
      await disconnect.mutateAsync();
    } catch (error) {
      setLastError(formatResult(error));
    }
  }

  async function handleSign() {
    setLastError("");
    try {
      await signMessage.mutateAsync({ message });
    } catch (error) {
      setLastError(formatResult(error));
    }
  }

  async function handleSend() {
    setLastError("");
    if (!amount.trim()) {
      setLastError("Invalid amount. Please input a number > 0.");
      return;
    }

    if (!to.trim()) {
      setLastError("Receiver account is required.");
      return;
    }

    try {
      await sendTransaction.mutateAsync({
        to: to.trim(),
        amount: amount.trim(),
        memo,
      });
    } catch (error) {
      setLastError(formatResult(error));
    }
  }

  function parseArgs(): unknown[] | null {
    try {
      const parsed = JSON.parse(argsText);
      if (!Array.isArray(parsed)) {
        setLastError("Contract args must be a JSON array.");
        return null;
      }
      return parsed;
    } catch {
      setLastError("Invalid JSON in contract args.");
      return null;
    }
  }

  async function handleWriteContract() {
    setLastError("");
    const args = parseArgs();
    if (!args) return;

    try {
      await writeContract.mutateAsync({ contract, action, args, approves: [{ token: 'iost', amount: '1' }] });
    } catch (error) {
      setLastError(formatResult(error));
    }
  }

  async function handleCallContract() {
    setLastError("");
    const args = parseArgs();
    if (!args) return;

    try {
      await callContract.mutateAsync({ contract, action, args, approves: [{ token: 'iost', amount: '1' }] });
    } catch (error) {
      setLastError(formatResult(error));
    }
  }

  async function handleGetNodeInfo() {
    setLastError("");
    setIsLoadingNodeInfo(true);
    try {
      const result = await publicClient.getNodeInfo();
      setNodeInfo(result);
    } catch (error) {
      setLastError(formatResult(error));
    } finally {
      setIsLoadingNodeInfo(false);
    }
  }

  return (
    <div className="demo-shell">
      <header>
        <h1>Ivem Kit React E2E Demo</h1>
        <p>For iost-iwallet-pro extension end-to-end flow testing (TanStack Query enabled).</p>
      </header>

      {!walletInstalled && (
        <section className="banner banner-warning">
          <strong>iWallet Pro not detected.</strong>
          <span>
            Please install/enable <code>iost-iwallet-pro</code>, then refresh
            this page.
          </span>
        </section>
      )}

      <section className="card">
        <h2>Wallet Status</h2>
        <div className="kv">
          <div>Installed</div>
          <div>{walletInstalled ? "Yes" : "No"}</div>
          <div>Connection</div>
          <div>{account.status}</div>
          <div>Chain</div>
          <div>{chainId}</div>
          <div>Account</div>
          <div>{account.address ?? "-"}</div>
        </div>
        <div className="row">
          <button
            onClick={handleReconnect}
            disabled={!walletInstalled || reconnect.isPending}
          >
            {reconnect.isPending ? "Reconnecting..." : "Reconnect"}
          </button>
          {!account.isConnected ? (
            <button
              onClick={handleConnect}
              disabled={!walletInstalled || connect.isPending}
            >
              {connect.isPending ? "Connecting..." : "Connect"}
            </button>
          ) : (
            <button onClick={handleDisconnect} disabled={disconnect.isPending}>
              {disconnect.isPending ? "Disconnecting..." : "Disconnect"}
            </button>
          )}
        </div>
      </section>

      <section className="card">
        <h2>Wallet Event Logs</h2>
        <div className="row">
          <button onClick={() => setEventLogs([])}>Clear Logs</button>
        </div>
        <div className="event-log">
          {eventLogs.length === 0 ? (
            <div className="muted">No wallet events yet.</div>
          ) : (
            eventLogs.map((log) => (
              <div key={log.id} className="event-item">
                <span className="event-time">{log.time}</span>
                <span className="event-name">{log.event}</span>
                <code>{log.payload || "-"}</code>
              </div>
            ))
          )}
        </div>
      </section>

      <section className="card">
        <h2>Sign Message</h2>
        <textarea
          value={message}
          onChange={(e) => setMessage(e.target.value)}
          rows={3}
          placeholder="message"
        />
        <div className="row">
          <button
            onClick={handleSign}
            disabled={!account.isConnected || signMessage.isPending}
          >
            {signMessage.isPending ? "Signing..." : "Sign"}
          </button>
        </div>
        {signMessage.data != null && (
          <pre className="result">{formatResult(signMessage.data)}</pre>
        )}
      </section>

      <section className="card">
        <h2>Send Transaction</h2>
        <div className="form-grid">
          <label>
            To
            <input value={to} onChange={(e) => setTo(e.target.value)} />
          </label>
          <label>
            Amount
            <input
              value={amount}
              onChange={(e) => setAmount(e.target.value)}
              inputMode="decimal"
            />
          </label>
          <label className="full">
            Memo
            <input value={memo} onChange={(e) => setMemo(e.target.value)} />
          </label>
        </div>
        <div className="row">
          <button
            onClick={handleSend}
            disabled={!account.isConnected || sendTransaction.isPending}
          >
            {sendTransaction.isPending ? "Sending..." : "Send"}
          </button>
        </div>
        {sendTransaction.data && (
          <pre className="result">{JSON.stringify(sendTransaction.data, null, 2)}</pre>
        )}
        {(sendTransaction.data || txReceipt || isWaitingReceipt) && (
          <div className="kv">
            <div>Last tx hash</div>
            <div>{sendTransaction.data?.hash ?? "-"}</div>
            <div>Receipt status</div>
            <div>{isWaitingReceipt ? "Waiting..." : txReceipt?.status_code ?? "-"}</div>
          </div>
        )}
      </section>

      <section className="card">
        <h2>Contract Tx</h2>
        <div className="form-grid">
          <label>
            Contract
            <input
              value={contract}
              onChange={(e) => setContract(e.target.value)}
            />
          </label>
          <label>
            Action
            <input value={action} onChange={(e) => setAction(e.target.value)} />
          </label>
          <label className="full">
            Args (JSON array)
            <textarea
              value={argsText}
              onChange={(e) => setArgsText(e.target.value)}
              rows={3}
            />
          </label>
        </div>
        <div className="row">
          <button
            onClick={handleWriteContract}
            disabled={!account.isConnected || writeContract.isPending}
          >
            {writeContract.isPending ? "Calling..." : "Write Contract"}
          </button>
          <button
            onClick={handleCallContract}
            disabled={!account.isConnected || callContract.isPending}
          >
            {callContract.isPending ? "Calling..." : "Call Contract"}
          </button>
        </div>
        {writeContract.data && (
          <pre className="result">{JSON.stringify(writeContract.data, null, 2)}</pre>
        )}
        {callContract.data && (
          <pre className="result">
            {JSON.stringify(callContract.data, null, 2)}
          </pre>
        )}
      </section>

      <section className="card">
        <h2>Public Client</h2>
        <div className="row">
          <button onClick={handleGetNodeInfo} disabled={isLoadingNodeInfo}>
            {isLoadingNodeInfo ? "Loading..." : "Get Node Info"}
          </button>
        </div>
        {nodeInfo != null && (
          <pre className="result">{JSON.stringify(nodeInfo, null, 2)}</pre>
        )}
      </section>

      {(lastError || requestErrors.length > 0) && (
        <section className="banner banner-error">
          <strong>Latest Error</strong>
          <pre className="result">
            {lastError || requestErrors[requestErrors.length - 1]}
          </pre>
        </section>
      )}
    </div>
  );
}

// playgrounds/vite-vue/src/App.vue
<template>
  <div class="demo-shell">
    <header>
      <h1>Ivem Kit Vue E2E Demo</h1>
      <p>For iost-iwallet-pro extension end-to-end flow testing (TanStack Query enabled).</p>
    </header>

    <section v-if="!walletInstalled" class="banner banner-warning">
      <strong>iWallet Pro not detected.</strong>
      <span>
        Please install/enable <code>iost-iwallet-pro</code>, then refresh this page.
      </span>
    </section>

    <section class="card">
      <h2>Wallet Status</h2>
      <div class="kv">
        <div>Installed</div>
        <div>{{ walletInstalled ? "Yes" : "No" }}</div>
        <div>Connection</div>
        <div>{{ account.status }}</div>
        <div>Chain</div>
        <div>{{ chainId }}</div>
        <div>Account</div>
        <div>{{ account.address || "-" }}</div>
      </div>
      <div class="row">
        <button @click="handleReconnect" :disabled="!walletInstalled || reconnectPending">
          {{ reconnectPending ? "Reconnecting..." : "Reconnect" }}
        </button>
        <button
          v-if="!account.isConnected"
          @click="handleConnect"
          :disabled="!walletInstalled || connectPending"
        >
          {{ connectPending ? "Connecting..." : "Connect" }}
        </button>
        <button v-else @click="handleDisconnect" :disabled="disconnectPending">
          {{ disconnectPending ? "Disconnecting..." : "Disconnect" }}
        </button>
      </div>
    </section>

    <section class="card">
      <h2>Wallet Event Logs</h2>
      <div class="row">
        <button @click="eventLogs = []">Clear Logs</button>
      </div>
      <div class="event-log">
        <div v-if="eventLogs.length === 0" class="muted">No wallet events yet.</div>
        <div v-for="log in eventLogs" :key="log.id" class="event-item">
          <span class="event-time">{{ log.time }}</span>
          <span class="event-name">{{ log.event }}</span>
          <code>{{ log.payload || "-" }}</code>
        </div>
      </div>
    </section>

    <section class="card">
      <h2>Sign Message</h2>
      <textarea v-model="message" rows="3" />
      <div class="row">
        <button @click="handleSign" :disabled="!account.isConnected || signPending">
          {{ signPending ? "Signing..." : "Sign" }}
        </button>
      </div>
      <pre v-if="signMessageData != null" class="result">{{ formattedSignData }}</pre>
    </section>

    <section class="card">
      <h2>Send Transaction</h2>
      <div class="form-grid">
        <label>
          To
          <input v-model="to" />
        </label>
        <label>
          Amount
          <input v-model="amount" inputmode="decimal" />
        </label>
        <label class="full">
          Memo
          <input v-model="memo" />
        </label>
      </div>
      <div class="row">
        <button @click="handleSend" :disabled="!account.isConnected || sendPending">
          {{ sendPending ? "Sending..." : "Send" }}
        </button>
      </div>
      <pre v-if="sendTransactionData != null" class="result">{{ formatResult(sendTransactionData) }}</pre>
    </section>

    <section class="card">
      <h2>Contract Tx</h2>
      <div class="form-grid">
        <label>
          Contract
          <input v-model="contract" />
        </label>
        <label>
          Action
          <input v-model="action" />
        </label>
        <label class="full">
          Args (JSON array)
          <textarea v-model="argsText" rows="3" />
        </label>
      </div>
      <div class="row">
        <button @click="handleWriteContract" :disabled="!account.isConnected || writePending">
          {{ writePending ? "Calling..." : "Write Contract" }}
        </button>
        <button @click="handleCallContract" :disabled="!account.isConnected || callContractPending">
          {{ callContractPending ? "Calling..." : "Call Contract" }}
        </button>
      </div>
      <pre v-if="writeContractData != null" class="result">{{ formatResult(writeContractData) }}</pre>
      <pre v-if="callContractData != null" class="result">{{ formatResult(callContractData) }}</pre>
    </section>

    <section class="card">
      <h2>Public Client</h2>
      <div class="row">
        <button @click="handleGetNodeInfo" :disabled="nodeInfoLoading">
          {{ nodeInfoLoading ? "Loading..." : "Get Node Info" }}
        </button>
      </div>
      <pre v-if="nodeInfo" class="result">{{ JSON.stringify(nodeInfo, null, 2) }}</pre>
    </section>

    <section v-if="latestError" class="banner banner-error">
      <strong>Latest Error</strong>
      <pre class="result">{{ latestError }}</pre>
    </section>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from "vue";
import { createPublicClient, http } from "@ivem/core";
import {
  mainnet,
  useAccount,
  useCallContract,
  useWriteContract,
  useChainId,
  useConnect,
  useDisconnect,
  useReconnect,
  useSendTransaction,
  useSignMessage,
} from "@ivem/kit-vue";

const publicClient = createPublicClient({
  chain: mainnet,
  transport: http(),
});

const account = useAccount();
const chainId = useChainId();
const connect = useConnect();
const reconnect = useReconnect();
const disconnect = useDisconnect();
const signMessage = useSignMessage();
const sendTransaction = useSendTransaction();
const writeContract = useWriteContract();
const callContract = useCallContract();

const walletInstalled = ref(false);
const latestError = ref("");
const eventLogs = ref<Array<{ id: number; time: string; event: string; payload: string }>>(
  []
);
let unbindWalletEvents: Array<() => void> = [];

const message = ref("Hello from Ivem Kit vite-vue");
const to = ref("");
const amount = ref("1");
const memo = ref("sent by Ivem Kit vite-vue");
const contract = ref("token.iost");
const action = ref("transfer");
const argsText = ref('["iost", "", "", "1", "write demo"]');

const nodeInfo = ref<unknown>(null);
const nodeInfoLoading = ref(false);

function formatResult(value: unknown) {
  if (value == null) return "";
  if (typeof value === "string") return value;
  if (value instanceof Error) {
    const code =
      typeof (value as Error & { code?: unknown }).code === "number"
        ? (value as Error & { code: number }).code
        : undefined;
    const baseMessage = code != null ? `[${code}] ${value.message}` : value.message;
    return value.stack ? `${baseMessage}\n${value.stack}` : baseMessage;
  }
  try {
    return JSON.stringify(value, null, 2);
  } catch {
    return String(value);
  }
}

const requestErrors = computed(() => {
  return [
    connect.error.value,
    reconnect.error.value,
    disconnect.error.value,
    signMessage.error.value,
    sendTransaction.error.value,
    writeContract.error.value,
    callContract.error.value,
  ]
    .filter(Boolean)
    .map((x) => formatResult(x));
});

const connectPending = computed(() => connect.isPending.value);
const reconnectPending = computed(() => reconnect.isPending.value);
const disconnectPending = computed(() => disconnect.isPending.value);
const signPending = computed(() => signMessage.isPending.value);
const sendPending = computed(() => sendTransaction.isPending.value);
const writePending = computed(() => writeContract.isPending.value);
const callContractPending = computed(() => callContract.isPending.value);

const signMessageData = computed(() => signMessage.data.value);
const sendTransactionData = computed(() => sendTransaction.data.value);
const writeContractData = computed(() => writeContract.data.value);
const callContractData = computed(() => callContract.data.value);

const formattedSignData = computed(() => {
  if (signMessageData.value == null) return "";
  return formatResult(signMessageData.value);
});

watch(requestErrors, (errors) => {
  if (errors.length > 0) {
    latestError.value = errors[errors.length - 1];
  }
});

watch(
  () => account.value.address,
  (address) => {
    if (address) {
      argsText.value = JSON.stringify([
        "iost",
        address,
        address,
        "1",
        "write demo",
      ]);
    }
  },
  { immediate: true }
);

function checkWallet() {
  walletInstalled.value = Boolean(window.IWalletJS?.isIWalletJS);

  for (const unbind of unbindWalletEvents) unbind();
  unbindWalletEvents = [];

  const provider = window.IWalletJS;
  if (!provider?.isIWalletJS) return;

  const events = [
    "accountChanged",
    "accountsChanged",
    "networkChanged",
    "pending",
    "success",
    "failed",
  ] as const;

  for (const event of events) {
    const handler = (payload: unknown) => {
      eventLogs.value = [
        {
          id: Date.now() + Math.floor(Math.random() * 10000),
          time: new Date().toLocaleTimeString(),
          event,
          payload: formatResult(payload),
        },
        ...eventLogs.value,
      ].slice(0, 80);
    };

    provider.on?.(event, handler);
    unbindWalletEvents.push(() => {
      provider.off?.(event, handler);
      provider.removeListener?.(event, handler);
    });
  }
}

onMounted(() => {
  checkWallet();
  window.addEventListener("focus", checkWallet);
});

onUnmounted(() => {
  window.removeEventListener("focus", checkWallet);
  for (const unbind of unbindWalletEvents) unbind();
  unbindWalletEvents = [];
});

async function handleConnect() {
  latestError.value = "";
  try {
    await connect.mutateAsync();
  } catch (error) {
    latestError.value = formatResult(error);
  }
}

async function handleReconnect() {
  latestError.value = "";
  try {
    await reconnect.mutateAsync();
  } catch (error) {
    latestError.value = formatResult(error);
  }
}

async function handleDisconnect() {
  latestError.value = "";
  try {
    await disconnect.mutateAsync();
  } catch (error) {
    latestError.value = formatResult(error);
  }
}

async function handleSign() {
  latestError.value = "";
  try {
    await signMessage.mutateAsync({ message: message.value });
  } catch (error) {
    latestError.value = formatResult(error);
  }
}

async function handleSend() {
  latestError.value = "";
  const parsedAmount = Number(amount.value);

  if (!Number.isFinite(parsedAmount) || parsedAmount <= 0) {
    latestError.value = "Invalid amount. Please input a number > 0.";
    return;
  }

  if (!to.value.trim()) {
    latestError.value = "Receiver account is required.";
    return;
  }

  try {
    await sendTransaction.mutateAsync({
      to: to.value.trim(),
      amount: amount.value.trim(),
      memo: memo.value,
    });
  } catch (error) {
    latestError.value = formatResult(error);
  }
}

function parseArgs(): unknown[] | null {
  try {
    const parsed = JSON.parse(argsText.value);
    if (!Array.isArray(parsed)) {
      latestError.value = "Contract args must be a JSON array.";
      return null;
    }
    return parsed;
  } catch {
    latestError.value = "Invalid JSON in contract args.";
    return null;
  }
}

async function handleWriteContract() {
  latestError.value = "";
  const args = parseArgs();
  if (!args) return;

  try {
    await writeContract.mutateAsync({
      contract: contract.value,
      action: action.value,
      args,
      approves:[
        {
          token:"iost",
          amount: "1",
        }
      ]
    });
  } catch (error) {
    latestError.value = formatResult(error);
  }
}

async function handleCallContract() {
  latestError.value = "";
  const args = parseArgs();
  if (!args) return;

  try {
    await callContract.mutateAsync({
      contract: contract.value,
      action: action.value,
      args,
      approves:[
        {
          token:"iost",
          amount: "1",
        }
      ]
    });
  } catch (error) {
    latestError.value = formatResult(error);
  }
}

async function handleGetNodeInfo() {
  latestError.value = "";
  nodeInfoLoading.value = true;
  try {
    nodeInfo.value = await publicClient.getNodeInfo();
  } catch (error) {
    latestError.value = formatResult(error);
  } finally {
    nodeInfoLoading.value = false;
  }
}
</script>
